/*
 * Notebook server for Teragrep Backend (nbs_01)
 * Copyright (C) 2025 Suomen Kanuuna Oy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 * Additional permission under GNU Affero General Public License version 3
 * section 7
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with other code, such other code is not for that reason alone subject to any
 * of the requirements of the GNU Affero GPL version 3 as long as this Program
 * is the same Program as licensed from Suomen Kanuuna Oy without any additional
 * modifications.
 *
 * Supplemented terms under GNU Affero General Public License version 3
 * section 7
 *
 * Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
 * versions must be marked as "Modified version of" The Program.
 *
 * Names of the licensors and authors may not be used for publicity purposes.
 *
 * No rights are granted for use of trade names, trademarks, or service marks
 * which are in The Program if any.
 *
 * Licensee must indemnify licensors and authors for any liability that these
 * contractual assumptions impose on licensors and authors.
 *
 * To the extent this program is licensed as part of the Commercial versions of
 * Teragrep, the applicable Commercial License may apply to this file if you as
 * a licensee so wish it.
 */
package com.teragrep.nbs_01.servlets;

import com.teragrep.nbs_01.endpoints.EndPoint;
import com.teragrep.nbs_01.requests.JsonRequest;
import com.teragrep.nbs_01.requests.Request;
import com.teragrep.nbs_01.responses.JsonResponse;
import jakarta.json.Json;
import jakarta.json.JsonObject;
import jakarta.json.JsonObjectBuilder;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.nio.charset.Charset;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Collectors;

// HTTPServlet that acts on the Filesystem to Find, Create, Delete and Update Notebooks, Directories and Paragraphs.
// Delegates each different HTTP request type to a different endpoint.
public final class FileSystemServlet extends jakarta.servlet.http.HttpServlet {

    private final EndPoint getEndPoint;
    private final EndPoint postEndPoint;
    private final EndPoint putEndPoint;
    private final EndPoint deleteEndPoint;
    private final Charset charset;

    // Servlet that assigns an endpoint for each of the supported HTTP request types (GET,POST,PUT,DELETE)
    public FileSystemServlet(
            EndPoint getEndPoint,
            EndPoint postEndPoint,
            EndPoint putEndPoint,
            EndPoint deleteEndPoint
    ) {
        this(getEndPoint, postEndPoint, putEndPoint, deleteEndPoint, Charset.defaultCharset());
    }

    public FileSystemServlet(
            EndPoint getEndPoint,
            EndPoint postEndPoint,
            EndPoint putEndPoint,
            EndPoint deleteEndPoint,
            Charset charset
    ) {
        super();
        this.getEndPoint = getEndPoint;
        this.postEndPoint = postEndPoint;
        this.putEndPoint = putEndPoint;
        this.deleteEndPoint = deleteEndPoint;
        this.charset = charset;
    }

    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // Extract the path of the requested file from the URL of the received request. getPathInfo() removes the path to the endpoint automatically, leaving only the file path specified after /{ContextPath}/{ServletPath}/.
        String pathString = req.getServletPath();
        Path path = Paths.get("/").relativize(Paths.get(pathString));
        Request endPointRequest = new JsonRequest("{\"path\":\"" + path + "\"}");

        // Transfer the Request to an EndPoint and create an HTTP response using the Response object generated by the Endpoint
        JsonResponse endPointResponse = getEndPoint.createResponse(endPointRequest);
        resp.setStatus(endPointResponse.status());
        resp.setContentType(endPointResponse.contentType());
        resp.setCharacterEncoding(charset.name());
        PrintWriter printWriter = resp.getWriter();
        printWriter.print(endPointResponse.body());
        printWriter.flush();
        printWriter.close();
    }

    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // Extract the path of the requested file from the URL of the received request. getPathInfo() removes the path to the endpoint automatically, leaving only the file path specified after /{ContextPath}/{ServLetPath}/.
        String pathString = req.getServletPath();
        Path path = Paths.get("/").relativize(Paths.get(pathString));

        // Read the body of the POST request. Request is expected to be in JSON.
        BufferedReader reader = req.getReader();
        String body = reader.lines().collect(Collectors.joining());
        reader.close();

        // Create an endPointRequest based on the body.
        JsonObjectBuilder jb = Json.createObjectBuilder(Json.createReader(new StringReader(body)).readObject());
        jb.add("path", path.toString());
        JsonObject json = jb.build();
        Request endPointRequest = new JsonRequest(json.toString());

        // Transfer the Request to an EndPoint and create an HTTP response using the Response object generated by the Endpoint
        JsonResponse endPointResponse = postEndPoint.createResponse(endPointRequest);

        resp.setStatus(endPointResponse.status());
        resp.setContentType(endPointResponse.contentType());
        resp.setCharacterEncoding(charset.name());
        PrintWriter writer = resp.getWriter();
        writer.write(endPointResponse.body().toString());
        writer.flush();
        writer.close();
    }

    protected void doPut(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // Extract the path of the requested file from the URL of the received request. getPathInfo() removes the path to the endpoint automatically, leaving only the file path specified after /{ContextPath}/{ServLetPath}/.
        String pathString = req.getServletPath();
        Path path = Paths.get("/").relativize(Paths.get(pathString));

        // Read the body of the PUT request
        BufferedReader reader = req.getReader();
        String body = reader.lines().collect(Collectors.joining());
        reader.close();
        // Create an endPointRequest based on the body.
        JsonObjectBuilder jb = Json.createObjectBuilder(Json.createReader(new StringReader(body)).readObject());
        jb.add("path", path.toString());
        JsonObject json = jb.build();

        // Create an endPointRequest based on the body. Body should contain JSON key-value pairs containing information about the resource.
        Request endPointRequest = new JsonRequest(json.toString());

        // Transfer the Request to an EndPoint and create an HTTP response using the Response object generated by the Endpoint
        JsonResponse endPointResponse = putEndPoint.createResponse(endPointRequest);
        resp.setStatus(endPointResponse.status());
        resp.setContentType(endPointResponse.contentType());
        resp.setCharacterEncoding(charset.name());
        PrintWriter writer = resp.getWriter();
        writer.write(endPointResponse.body().toString());
        writer.flush();
        writer.close();
    }

    protected void doDelete(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        // Extract the path of the requested file from the URL of the received request. getPathInfo() removes the path to the endpoint automatically, leaving only the file path specified after /{ContextPath}/{ServLetPath}/.
        String pathString = req.getServletPath();
        Path path = Paths.get("/").relativize(Paths.get(pathString));
        Request endPointRequest = new JsonRequest("{\"path\":\"" + path + "\"}");

        // Transfer the Request to an EndPoint and create an HTTP response using the Response object generated by the Endpoint
        JsonResponse endPointResponse = deleteEndPoint.createResponse(endPointRequest);
        resp.setStatus(endPointResponse.status());
        resp.setContentType(endPointResponse.contentType());
        resp.setCharacterEncoding(charset.name());
        PrintWriter writer = resp.getWriter();
        writer.write(endPointResponse.body().toString());
        writer.flush();
        writer.close();
    }
}
